### ISSUE TITLE
Source for Medial Axis Transform Algorithm

### ISSUE THREAD

**Issue by PieceMaker** [nraynaud/polygonsJS#1]
I have been digging through the code for computing a medial axis and am quite impressed. However, I would like to have read about the implemented algorithm so I can have a better understanding of how/why each piece works in order. Is a source publication/citation available for the algorithm that is implemented in the code?

**Comment by nraynaud** [comment]
Yes, I fond the algorithm on the internet, but when I wanted to find it again to put it in a comment, I could not find it again.

Today I got lucky with google, here is the source:
http://maptools.home.comcast.net/~maptools/Skeleton.pdf

**Comment by PieceMaker** [comment]
Much appreciated!

**Comment by nraynaud** [comment]
I think I forgot to tell you a very essential information: my implementation doesn't work, there are bugs.

**Comment by PieceMaker** [comment]
Thank you very much for letting me know. I will make sure whatever possible application of this gets thoroughly tested and sufficient error handling implemented.
